### ISSUE TITLE
Lacking paper that describes the model

### ISSUE THREAD

**Issue by yui-ishihara** [HIT-ICES/AL-NER#2]
Hi,

I find your code quite related to my current research. But it seems that there is no mention of corresponding paper to describe the model architecture, experiment, etc. Could you provide the link to the paper if there is any?

Thanks
Yui

**Comment by icecity96** [comment]
We have release our paper on arxiv. https://arxiv.org/abs/2001.02524

And a enhance version have been submitted to Applied Intelligence (under review) [This enhanced version will be updated to arXiv]

@misc{liu2020ltp,
      title={LTP: A New Active Learning Strategy for CRF-Based Named Entity Recognition}, 
      author={Mingyi Liu and Zhiying Tu and Tong Zhang and Tonghua Su and Zhongjie Wang},
      year={2020},
      eprint={2001.02524},
      archivePrefix={arXiv},
      primaryClass={cs.CL}
}
