### ISSUE TITLE
License of the code base

### ISSUE THREAD

**Issue by yui-ishihara** [HIT-ICES/AL-NER#3]
Hi,

I find your implementations pretty modular and extensible. It is very well worth learning from in the project I am currently working on. But I could not find license in your repository to specify what I need to reuse part of your code. Is there any possibility a license added to your repository.

Cheers,
Yui

**Comment by icecity96** [comment]
Feel free to reuse our code, and if our code or paper help your research, please cite our work:

```
@misc{liu2020ltp,
title={LTP: A New Active Learning Strategy for CRF-Based Named Entity Recognition},
author={Mingyi Liu and Zhiying Tu and Tong Zhang and Tonghua Su and Zhongjie Wang},
year={2020},
eprint={2001.02524},
archivePrefix={arXiv},
primaryClass={cs.CL}
}
```
