### ISSUE TITLE
reproducing results on CONLL2003

### ISSUE THREAD

**Issue by sunnyrahul25** [HIT-ICES/AL-NER#4]
Thank you for sharing the code.
I am trying to reproduce the results for conll2003 dateset as mentioned in the paper. 
I am not able to reproduce the exact statistics for the conll2003 datset as mentioned in the paper and the Readme.
The data stat from [datasets](https://huggingface.co/datasets/conll2003)
conll2003 | 14041 | 3250 | 3453

Could you please share your preprocessing script?

**Comment by icecity96** [comment]
Could you provide more details? What are your results?
I'm not sure whether the pre-processing scripts are still in place, I'll confirm when I get back to school (currently over winter break.) BTW, I noticed that your data download source seems to be different from the source provided in our README, which could also potentially make some difference.

**Comment by sunnyrahul25** [comment]
I will try to  run the code again with the data source mentioned in the README and update you on the results.
