### ISSUE TITLE
关于数据集相关统计量数据

### ISSUE THREAD

**Issue by zhw666888** [HIT-ICES/AL-NER#5]
您好，我按照你们给出的数据集和数据处理方法，似乎得不到和你们一致的数据集统计相关数据，不知为何？

**Comment by icecity96** [comment]
Could you provide more details? What are your results?

**Comment by zhw666888** [comment]
比如那些长度大于64的句子被逗号分割或者截断处理，这种情况下#s、#t等数据统计结果和论文中的不一致，请问我是不是忽略了什么细节？
