### ISSUE TITLE
inconsistent length of test tags

### ISSUE THREAD

**Issue by jxliu-vivian** [HIT-ICES/AL-NER#6]
Hi,

I am trying to apply your code to CONLL 2003 datasets and my own datasets.
However, it yields the following error:
 ValueError: Found input variables with inconsistent numbers of samples:

I found it's becasue when the model predicts on the test datasets, the length of predicted labels and the length of truth labels doesn't match for some of the sentences. In this way, it cannot calculate the F1 score.

Do you have any idea about why this happens? Thanks!

Best regards,
Jiaxing

**Comment by icecity96** [comment]
This code is a long time ago, and my guess is that the problem you are having is due to incorrect test set formatting. (Probably missing/more [CLS], [SEP]...)
